# Generated by Django 5.2.8 on 2026-03-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swaprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
