# Generated by Django 5.2.8 on 2026-03-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_location_alter_job_skills_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
