# Generated by Django 5.2.8 on 2026-03-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full time', 'Full Time'), ('part time', 'Part Time'), ('internship', 'Internship')], max_length=20),
        ),
    ]
