# Generated by Django 5.2.8 on 2026-03-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='email',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
    ]
