# Generated by Django 5.2.8 on 2026-03-24 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobapplication_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='email',
        ),
    ]
