# Generated by Django 6.0.3 on 2026-03-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_jobapplication_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='ats_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ats_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
