# Generated by Django 6.0.3 on 2026-04-03 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_jobapplication_interview_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='intrview_link',
            new_name='interview_link',
        ),
    ]
