# Generated by Django 5.2.8 on 2026-03-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0002_alter_userprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('recruiter', 'Recruiter'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
