services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
      - redis

  celery:
    build: .
    env_file:
      - .env
    command: ["celery", "-A", "skillswap", "worker", "-l", "info", "-P", "solo", "--uid=nobody"]
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SETTINGS_MODULE=skillswap.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - HF_HOME=/tmp/huggingface
      - TRANSFORMERS_CACHE=/tmp/huggingface
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    env_file:
      - .env
    command: ["celery", "-A", "skillswap", "beat", "-l", "info"]
    environment:
      - DJANGO_SETTINGS_MODULE=skillswap.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DB_HOST=db
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

volumes:
  postgres_data: