# Generated by Django 5.2.8 on 2026-03-17 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('swapsystem', '0002_alter_swaprequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('swap_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='swapsystem.swaprequest')),
            ],
        ),
    ]
