# Generated by Django 5.2.8 on 2026-03-18 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_chatmessage'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='message',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='communication',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='conversation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatapp.conversation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='user1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_user1', to='userprofile.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='user2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_user2', to='userprofile.profile'),
            preserve_default=False,
        ),
    ]
