# Generated by Django 5.2.8 on 2026-03-18 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_rename_message_chatmessage_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='created_at',
            new_name='create_at',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user2',
        ),
        migrations.DeleteModel(
            name='chatMessage',
        ),
    ]
