# Generated by Django 5.2.8 on 2026-03-09 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='locatio',
            new_name='location',
        ),
    ]
