# Generated by Django 5.2.8 on 2026-03-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
