# Generated by Django 5.2.8 on 2026-03-10 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_profile_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill_wanted',
            name='name',
        ),
        migrations.RemoveField(
            model_name='skilloffered',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='skill_wanted',
            name='category',
        ),
        migrations.RemoveField(
            model_name='skill_wanted',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skilloffered',
            name='user',
        ),
        migrations.DeleteModel(
            name='skill',
        ),
        migrations.DeleteModel(
            name='SkillCategory',
        ),
        migrations.DeleteModel(
            name='skill_wanted',
        ),
        migrations.DeleteModel(
            name='skilloffered',
        ),
    ]
