# Generated by Django 5.2.8 on 2026-03-09 11:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilloffered',
            name='name',
        ),
        migrations.AddField(
            model_name='skill_wanted',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='skilloffered',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skilloffered',
            name='experience_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skilloffered',
            name='skills',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userprofile.skill'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill_wanted',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.skill'),
        ),
    ]
