# Generated by Django 5.2.8 on 2026-03-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionfeedback',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
