# Generated by Django 5.2.8 on 2026-03-19 07:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_alter_sessionfeedback_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionfeedback',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
